# version: "3.8"

x-cuda_learning_mojo_base: &cuda_learning_mojo_base
  working_dir: /home/mojo_user/cuda_learning_mojo
  logging:
    driver: json-file
    options:
      max-size: 50m
  stdin_open: true
  tty: true
  shm_size: 16000000000
  ports:
    - "5900:5900"
  volumes:
    - .:/home/mojo_user/cuda_learning_mojo/
    - ~/.ssh:/home/mojo_user/.ssh:rw
    - cuda_learning_mojo_vscode_data_cache:/home/mojo_user/.vscode-server/data/User/globalStorage:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
  environment:
    PIXI_ENVIRONMENT_NAME: ${PIXI_ENVIRONMENT_NAME:-default}
    DISPLAY: host.docker.internal:0

volumes:
  cuda_learning_mojo_vscode_data_cache:
      external: false

services:
  cuda_learning_mojo_arm64_cpu: &cuda_learning_mojo_arm64_cpu
    <<: *cuda_learning_mojo_base
    profiles: ["arm64_cpu"]
    restart: unless-stopped
    platform: linux/arm64
    image: josiahls/c_binder_mojo-arm64-cpu:${VERSION:-latest}

  cuda_learning_mojo_arm64_gpu: &cuda_learning_mojo_arm64_gpu
    <<: *cuda_learning_mojo_arm64_cpu
    profiles: ["arm64_gpu"]
    image: josiahls/c_binder_mojo-arm64-gpu:${VERSION:-latest}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  cuda_learning_mojo_x86_64_cpu: &cuda_learning_mojo_x86_64_cpu
    <<: *cuda_learning_mojo_base
    profiles: ["x86_64_cpu"]
    restart: unless-stopped
    platform: linux/amd64
    image: josiahls/c_binder_mojo-x86_64-cpu:${VERSION:-latest}

  cuda_learning_mojo_x86_64_gpu: &c_binder_mojo_x86_64_gpu
    <<: *cuda_learning_mojo_x86_64_cpu
    profiles: ["x86_64_gpu"]
    image: josiahls/c_binder_mojo-x86_64-gpu:${VERSION:-latest}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  

